config/routes.rb
Rails.application.routes.draw do

  # get 'subjects/index'
  # get 'teachers/index'
  # get 'tutions/index'
  # get 'projects/index'
  # get 'companies/index'
  # root 'authors#index'

  resources :authors
  # get 'bs/index', to: 'bs#index'
  # get 'bs/new', to: 'bs#new'
  resources :books
  # project_add_form_field_path

  root 'companies#index'

  resources :companies 
  resources :projects

  
  resources :tutions
  resources :subjects
  resources :teachers
  resources :students  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books, dependent: :delete_all
    accepts_nested_attributes_for :books

    enum gender: [ :male, :female ]
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author

  def author_name
    author.name
  end
end

app/models/company.rb
class Company < ApplicationRecord
    has_and_belongs_to_many :projects
    accepts_nested_attributes_for :projects
end

app/models/emp.rb
class Emp < ApplicationRecord
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
    has_and_belongs_to_many :companies
end

app/models/student.rb
class Student < ApplicationRecord
    has_and_belongs_to_many :subjects
end

app/models/subject.rb
class Subject < ApplicationRecord
    belongs_to :connected_by, polymorphic: true
    has_many :teachers
    has_and_belongs_to_many :students
end

app/models/teacher.rb
class Teacher < ApplicationRecord
    belongs_to :connected_by, polymorphic: true, required: false
	belongs_to :subject, required: false
    # after_create :randomize_id
    before_create :assign_tution

	private
	def randomize_id
  	puts Tution.all.sample
  	update(connected_by: Tution.all.sample)    
  	puts "Updated"
	end

	def assign_tution
		self.connected_by = Tution.all.sample
	end
end


   

app/models/tution.rb
class Tution < ApplicationRecord
  has_many :teachers, as: :connected_by, dependent: :delete_all
  has_many :subjects, as: :connected_by, dependent: :delete_all
  # validates_uniqueness_of :name, :address
  # after_create_commit :publish
  # before_validation :remove_whitespaces
  validates :name, length: { minimum: 6 }
  after_validation :set_status
  after_create :randomize_id

 



  private

  def randomize_id
    puts ""
  end




  # def remove_whitespaces
  
  # end

  def set_status
      puts "name is: #{self.name}"
      # self.Tution.delete(id)
      # @tution=Tution.all
      # @tution.map{|name| puts name.name}
      # @name=Tution.name
      # @name.destroy
      # puts "After create it destroyed"
  end

    # def publish
    #   puts 'updating'
    #   update(name: "darshan thakor")
    #   puts 'updated successfully'
    # end

    # def post_on_social_media
    #   puts 'posting on social media'
    # end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors=Author.all
  end

  def new
    @author=Author.new
    @author.books.build 
   
    # 1.times { @author.books.build }
  end

  def create
    @author=Author.create(author_params)
      redirect_to root_path
  end

  def destroy
    @author=Author.find(params[:id])
   
    @author.destroy
    redirect_to root_path
  end

  private
    def author_params
      params.require(:author).permit( :name, :bdate, :gender, books_attributes:[:name])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books=Book.all
    @book = Book.new
  end


  def create
    @book=Book.create(book_params)
    redirect_to books_path
  end


  private
    def book_params
      params.require(:book).permit(:name,:author_id)
    end
end

app/controllers/tutions_controller.rb
class TutionsController < ApplicationController
  def index
    @tution=Tution.new
    # @tution.teachers.build
    # @tution.subjects.build 
    @tutions=Tution.all
   
  end

  def create
    @tution=Tution.create(tution_params)
    redirect_to tutions_path
  end

  def destroy
    @tution=Tution.find(params[:id])
    @tution.destroy
    redirect_to tutions_path
  end


  private
    def tution_params
      params.require(:tution).permit(:name,:address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/tutions_helper.rb
module TutionsHelper
end

app/views/authors/_form.html.erb
 <%= form_with model: @author, local: false do |form| %>
    <div>
        <strong>Authorname</strong>
        <%= form.text_field :name, class:'form-control' %>
    </div>

    <div>
        <strong>AuthorBirthDate</strong>
        <%= form.date_field :bdate, class:'form-control'%>
    </div>
    
    <div class="jsBooks">
        <%= form.fields_for :books do |books_form| %>
            <%= render 'nested_form', form: books_form %>
        <%end%>
    </div>

    <div>
        <strong>select author gender</strong>
       <% Author.genders.keys.each do |gender| %>
            <%= form.radio_button :gender, gender %>
            <%= form.label :gender, gender %>
        <% end %>
    </div>  

    <%= link_to "Add book", "javascript:void(0);", id: "addBook"%><br>
    <%= form.submit 'submit', class: 'btn btn-primary' %>

<% end %>



            

app/views/authors/_nested_form.html.erb
<div id="nestedFields">
    <strong>Book Name</strong>
    <%= form.text_field :name, class:'form-control book-name' %> 
</div>
    

app/views/authors/index.html.erb
<div class="container">
<%= link_to "New Author",new_author_path, class:'btn btn-success my-2' %>
<%= link_to "New Book",books_path, class:'btn btn-success my-2'%>


 

<table class="table">
  <thead>
    <tr>
      <th>Id</th>
      <th scope="col">name</th>
      <th scope="col">Birthdate</th>
      <th>Book</th>
      <th>Gender</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
  <% @authors.each do |author| %>
    <tr>
        <td><%= author.id %></td>
        <td><%= author.name %></td>
        <td><%= author.bdate %></td>
        <td><%= author.books.pluck(:name).reject(&:blank?).join(',') %></td>
         <td><%= author.gender %></td>
      <td><%= link_to 'Delete', author_path(author), method: :delete %></td>
    </tr>
    <%end%> 
  </tbody>
</table>
</div>

    

app/views/authors/new.html.erb
<div class="container">
    <%= render 'form' %>
</div>

app/views/books/index.html.erb
<div class="container">
  <h3>Create your Book here</h3>
  
  <%= render 'partials/bform' %>

  <table class="table ">
    <tr>
        <th>Author Name</th>
        <th>Books</th>
    </tr>
    <%@books.each do |book|%>
      <tr>
          <td><%= book.author_name %></td>
          <td><%= book.name %></td>
      </tr>
    <%end%>
  </table>
        
</div>

app/views/tutions/_form.html.erb
<section>
    <%= form_with model: @tution do |form| %>
    <div class="fields">
        <strong>Tution Name</strong>
        <%= form.text_field :name, class:'form-control'%>
    </div>

    <div class="fields">
        <strong>Tution Address</strong>
        <%= form.text_field :address, class:'form-control' %>
    </div>

    <div class="fields">
        <%= form.submit class:'btn btn-primary my-2'  %>
    </div>
<%end%>
</section>

app/views/tutions/index.html.erb
<div class="container my-3">
    <%= link_to 'Teacher',teachers_path, class: 'btn btn-primary' %>
    <%= link_to 'Subject' ,subjects_path, class: 'btn btn-primary'  %>

    <h3>Create Tution</h3>
    <%= render 'form'%>
    <table class="table">
        <tr>
            <th>Tution Name</th>
            <th>Tution Address</th>
            <th>Teachers</th>
            <th>Subjects</th>
            <th>Delete</th>
        </tr>

        <%@tutions.each do |tution|%>
        <tr>
            <td><%= tution.name %></td>
            <td><%= tution.address %></td>
            <td><%= tution.teachers.pluck(:name).join(',') %></td>
            <td><%= tution.subjects.pluck(:name).join(',') %></td>
            <td><%= link_to 'Delete', tution_path(tution), method: :delete %></td>
        </tr>
        <%end%>
    </table>
</div>