config/routes.rb
Rails.application.routes.draw do

  # get 'subjects/index'
  # get 'teachers/index'
  # get 'tutions/index'
  # get 'projects/index'
  # get 'companies/index'
  # root 'authors#index'

  resources :authors
  # get 'bs/index', to: 'bs#index'
  # get 'bs/new', to: 'bs#new'
  resources :books
  # project_add_form_field_path

  root 'companies#index'

  resources :companies 
  resources :projects

  
  resources :tutions
  resources :subjects
  resources :teachers
  resources :students  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books, dependent: :delete_all
    accepts_nested_attributes_for :books

    enum gender: [ :male, :female ]
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author

  def author_name
    author.name
  end
end

app/models/company.rb
class Company < ApplicationRecord
    has_and_belongs_to_many :projects
    accepts_nested_attributes_for :projects
end

app/models/emp.rb
class Emp < ApplicationRecord
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
    has_and_belongs_to_many :companies
end

app/models/student.rb
class Student < ApplicationRecord
    has_and_belongs_to_many :subjects
end

app/models/subject.rb
class Subject < ApplicationRecord
    belongs_to :connected_by, polymorphic: true
    has_many :teachers
    has_and_belongs_to_many :students
end

app/models/teacher.rb
class Teacher < ApplicationRecord
    belongs_to :connected_by, polymorphic: true, required: false
	belongs_to :subject, required: false
    # after_create :randomize_id
    before_create :assign_tution

	private
	def randomize_id
  	puts Tution.all.sample
  	update(connected_by: Tution.all.sample)    
  	puts "Updated"
	end

	def assign_tution
		self.connected_by = Tution.all.sample
	end
end


   

app/models/tution.rb
class Tution < ApplicationRecord
  has_many :teachers, as: :connected_by, dependent: :delete_all
  has_many :subjects, as: :connected_by, dependent: :delete_all
  # validates_uniqueness_of :name, :address
  # after_create_commit :publish
  # before_validation :remove_whitespaces
  validates :name, length: { minimum: 6 }
  after_validation :set_status
  after_create :randomize_id

 



  private

  def randomize_id
    puts ""
  end




  # def remove_whitespaces
  
  # end

  def set_status
      puts "name is: #{self.name}"
      # self.Tution.delete(id)
      # @tution=Tution.all
      # @tution.map{|name| puts name.name}
      # @name=Tution.name
      # @name.destroy
      # puts "After create it destroyed"
  end

    # def publish
    #   puts 'updating'
    #   update(name: "darshan thakor")
    #   puts 'updated successfully'
    # end

    # def post_on_social_media
    #   puts 'posting on social media'
    # end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors=Author.all
  end

  def new
    @author=Author.new
    @author.books.build 
   
    # 1.times { @author.books.build }
  end

  def create
    @author=Author.create(author_params)
      redirect_to root_path
  end

  def destroy
    @author=Author.find(params[:id])
   
    @author.destroy
    redirect_to root_path
  end

  private
    def author_params
      params.require(:author).permit( :name, :bdate, :gender, books_attributes:[:name])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books=Book.all
    @book = Book.new
  end


  def create
    @book=Book.create(book_params)
    redirect_to books_path
  end


  private
    def book_params
      params.require(:book).permit(:name,:author_id)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects=Project.all
    @project=Project.new
  end


  def edit
    @project=Project.find(params[:id])
  end

  def create
    @project=Project.create( project_params)
    redirect_to projects_path
  end

  def update
    @project=Project.find(params[:id])
    if @project.update(project_params)
      redirect_to projects_path
    end
  end

  def destroy
    @project=Project.find(params[:id])
    @project.destroy
    redirect_to projects_path
  end

  private
    def project_params
      params.require(:project).permit(:name,company_ids: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/tutions_helper.rb
module TutionsHelper
end

app/views/projects/_form.html.erb
<%= form_with model: @project do |form| %>
    <div>
        <strong>Project Name</strong>
        <%= form.text_field :name, class:'form-control'%>
    </div>

    
  
    <strong>Select Company</strong>

    <div class="row">
            <%= collection_check_boxes(:project, :company_ids, Company.all,:id,:name) do |b|%>
                <%#=b.inspect%>
                    <%= b.label class:"label-checkbox" do%>
                    <%= b.text!="" ? b.check_box + b.text : "" %>
                <%end%> 
            <%end%>
        </div>
    <div>
        <%= form.submit class:'btn btn-success my-3' %>
    </div>
<%end%>

app/views/projects/edit.html.erb
<%= render 'form' %>

app/views/projects/index.html.erb
<div class="container my-3">
<%= render 'form' %>

    <table class="table">
        <tr>
            <th>Project Name</th>
            <th>Project Companies</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>

        <% @projects.each do |project| %>
            <tr>
                <td><%= project.name %></td>
                <td><%= project.companies.pluck(:name).reject(&:blank?).join(',') %></td>    
                <td><%= link_to 'Edit', edit_project_path(project) %></td>
                <td><%= link_to 'Delete',project_path(project), method: :delete %></td>
            </tr>
        <% end %>
    </table>

</div>

    