config/routes.rb
Rails.application.routes.draw do

  # get 'subjects/index'
  # get 'teachers/index'
  # get 'tutions/index'
  # get 'projects/index'
  # get 'companies/index'
  # root 'authors#index'

  resources :authors
  # get 'bs/index', to: 'bs#index'
  # get 'bs/new', to: 'bs#new'
  resources :books
  # project_add_form_field_path

  root 'companies#index'

  resources :companies 
  resources :projects

  
  resources :tutions
  resources :subjects
  resources :teachers
  resources :students  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books, dependent: :delete_all
    accepts_nested_attributes_for :books

    enum gender: [ :male, :female ]
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author

  def author_name
    author.name
  end
end

app/models/company.rb
class Company < ApplicationRecord
    has_and_belongs_to_many :projects
    accepts_nested_attributes_for :projects
end

app/models/emp.rb
class Emp < ApplicationRecord
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
    has_and_belongs_to_many :companies
end

app/models/student.rb
class Student < ApplicationRecord
    has_and_belongs_to_many :subjects
end

app/models/subject.rb
class Subject < ApplicationRecord
    belongs_to :connected_by, polymorphic: true
    has_many :teachers
    has_and_belongs_to_many :students
end

app/models/teacher.rb
class Teacher < ApplicationRecord
    belongs_to :connected_by, polymorphic: true, required: false
	belongs_to :subject, required: false
    # after_create :randomize_id
    before_create :assign_tution

	private
	def randomize_id
  	puts Tution.all.sample
  	update(connected_by: Tution.all.sample)    
  	puts "Updated"
	end

	def assign_tution
		self.connected_by = Tution.all.sample
	end
end


   

app/models/tution.rb
class Tution < ApplicationRecord
  has_many :teachers, as: :connected_by, dependent: :delete_all
  has_many :subjects, as: :connected_by, dependent: :delete_all
  # validates_uniqueness_of :name, :address
  # after_create_commit :publish
  # before_validation :remove_whitespaces
  validates :name, length: { minimum: 6 }
  after_validation :set_status
  after_create :randomize_id

 



  private

  def randomize_id
    puts ""
  end




  # def remove_whitespaces
  
  # end

  def set_status
      puts "name is: #{self.name}"
      # self.Tution.delete(id)
      # @tution=Tution.all
      # @tution.map{|name| puts name.name}
      # @name=Tution.name
      # @name.destroy
      # puts "After create it destroyed"
  end

    # def publish
    #   puts 'updating'
    #   update(name: "darshan thakor")
    #   puts 'updated successfully'
    # end

    # def post_on_social_media
    #   puts 'posting on social media'
    # end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors=Author.all
  end

  def new
    @author=Author.new
    @author.books.build 
   
    # 1.times { @author.books.build }
  end

  def create
    @author=Author.create(author_params)
      redirect_to root_path
  end

  def destroy
    @author=Author.find(params[:id])
   
    @author.destroy
    redirect_to root_path
  end

  private
    def author_params
      params.require(:author).permit( :name, :bdate, :gender, books_attributes:[:name])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books=Book.all
    @book = Book.new
  end


  def create
    @book=Book.create(book_params)
    redirect_to books_path
  end


  private
    def book_params
      params.require(:book).permit(:name,:author_id)
    end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies=Company.all
   
  end
  def new
    @company=Company.new
  end

  def edit
    @company=Company.find(params[:id])
  end

  def update
    @company=Company.find(params[:id])
    if @company.update(company_params)
      #redirect_to root_path
      respond_to do |format|
        format.js
      end
    end
  end

  def create
    @company=Company.create!(company_params)
    # redirect_to root_path
    respond_to do |format|
      format.js 
    end
  end

  def destroy
    @company=Company.find(params[:id])
    @company.destroy
    redirect_to root_path
  end

  private
    def company_params
      params.require(:company).permit(:name, :e_count, :address,project_ids: [])
    end

    # def create_projects
    #   project_params = params[:company][:projects]
    #   projects = []
    #   project_params.each do |i, form_params|
    #     form_params.permit!
    #     projects << Project.create(form_params)
    #   end
    #   @company.projects << projects
    # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/tutions_helper.rb
module TutionsHelper
end

app/views/companies/_company.html.erb
    <tr id=<%= "company-#{company.id}" %>>
        <td><%= company.name %></td>
        <td><%= company.e_count %></td>
        <td><%= company.address %></td>
        <td><%= company.projects.pluck(:name).reject(&:blank?).join(',') %></td>    
        <td><%= link_to 'Edit', edit_company_path(company), remote: true, class: 'edit' %></td>
        <td><%= link_to 'Delete', company_path(company), method: :delete %></td>
    </tr>

app/views/companies/_form.html.erb
 <%= form_with model: @company, local: false do |form| %>
    <div>
        <strong>Company Name</strong>
        <%= form.text_field :name, class:'form-control'%>
    </div>

    <div>
        <strong>Company Employees Number</strong>
        <%= form.text_field :e_count, class:'form-control' %>
    </div>

    <div>
        <strong>Company Address</strong>
        <%= form.text_field :address, class:'form-control' %>
    </div>

            <strong>Select Project</strong>

    <div class="row">
            <%= collection_check_boxes(:company, :project_ids, Project.all,:id,:name) do |b|%>
                <%#=b.inspect%>
                    <%= b.label class:"label-checkbox" do%>
                    <%= b.text!="" ? b.check_box + b.text : "" %>
                <%end%> 
            <%end%>
        </div>

    <div>
        <%= form.submit class:'btn btn-success my-3' %>
    </div>
<%end%>

app/views/companies/create.js.erb
$(".my-data").append("<%= j render partial:'company', locals: {company: @company} %>")

app/views/companies/edit.html.erb
<%= render 'form' %>

app/views/companies/edit.js.erb
$( document ).ready(function() {
    $('.edit').click(function(){
        $("#Model").find(".modal-body").html("<%= j render partial: 'form' %>");
        $("#Model").modal("show");    
    }) 
});
    

app/views/companies/index.html.erb
<div class="container my-3">
    <%= link_to 'Projects', projects_path, class: 'btn btn-primary' %><br>
    <%= link_to "Add Company",new_company_path,class:'btn btn-primary my-2 add', remote: true %>

<div id="Model" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title" id="myModalLabel">Form</h4>
            <button type="button" class="close btn btn-secondary btn-sm" data-bs-dismiss="modal">close</button>  
        </div>
        <div class="modal-body">
        </div>
        
    </div>
  </div>
</div>


<div id="Form">

</div>

    <table class="table">
        <tr>
            <th>Company Name</th>
            <th>Company Employees</th>
            <th>Company Address</th>
            <th>Projects</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>

        <tbody class="my-data">
            <%= render partial: 'company', collection: @companies%>
        </tbody>
    </table>

</div>



<!-- Modal -->




    

app/views/companies/new.js.erb
$( document ).ready(function() {
    $('.add').click(function(){
        
        $("#Model").find(".modal-body").html("<%= j render partial: 'form' %>");
        $("#Model").modal("show");    
    })
});

console.log('working new');
    

// $(document).on("page:change", function() {
    
//   });

app/views/companies/update.js.erb
console.log('update is working');
$('#company-<%= @company.id %>').replaceWith("<%= j render partial:'company', locals: {company: @company} %>")
console.log("<%= @company.id %>")